%SETSPEC Set spectrum for pseudo-Euclidean dataset or mapping
%
%   B = SETSPEC(A,SPEC)
%   B = A*SETSPEC([],SPEC);
%
% INPUT
%   A    Dataset
%   SPEC Spectrum, ranked eigenvalues of the pseudo-Euclidean mapping
%
% OUTPUT
%   B   PE dataset
%
% DESCRIPTION
% In the computation of a pseudo-Euclidean embedding by PE_EM a set of
% eigenvalues is encountered that is partially positive and partially
% negative. The ranked set of eigenvalues, from most positive to most
% negative is called the spectrum. It characterizes the PE embedding and
% the original dissimilarity matrix. This routines stores this spectrum in
% a PE dataset generated by such a mapping. It may be retrieved by GETSPEC
% and plotted by PLOTSPEC
%
% SEE ALSO
% DATASETS, MAPPINGS, PE_EM, GETSPEC, PLOTSPEC

% Copyright: R.P.W. Duin, r.p.w.duin@prtools.org
% Faculty EWI, Delft University of Technology
% P.O. Box 5031, 2600 GA Delft, The Netherlands

function b = setspec(a,spec)

  if nargin < 1 | isempty(a)
    b = prmapping(mfilename,'fixed',{spec});
  else
    b = setuser(prdataset(a),spec,'pe_spectrum');
  end
  
return
  
  
  
